name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:
    runs-on: [ubuntu-latest]
    steps:
    - name : Checkout source
      uses : actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run : docker build -t demo1 .
    - name : Publish image to docker hub
      run : docker push demo1:latest

  deploy:
    needs : build
    runs-on : [aws-ec2]
    steps:
      - name : Pull image from docker hub
        run: docker pull demo1:latest
      - name : Delete old container
        run : docker rm -f app-container
      - name : Run docker container
        run : docker run -d -p 80:5000 -name app-container demo1


